export const flaggedIssues = [
  {
    id: "ABC-232",
    date: "05 July 2025, 10:00 AM",
    timestamp: "2025-07-05T10:00:00",
    school: "GreenTown High School",
    reporter: "Mr. Danial, Teacher",
    category: "Infrastructure",
    status: "In Progress",
    room: "10th - Room 101",
    description: "Ceiling Fan not working in Room 101",
    attachmentUrl: "/fan_issue.jpg",
  },
  {
    id: "DEF-104",
    date: "06 July 2025, 02:15 PM",
    timestamp: "2025-07-06T14:15:00",
    school: "BlueBell Public School",
    reporter: "Ms. Anita, Student",
    category: "Sanitation",
    status: "Pending",
    room: "8th - Girls Washroom",
    description: "No water supply in girls washroom",
    attachmentUrl: "/washroom_issue.jpg",
  },
  {
    id: "GHI-765",
    date: "07 July 2025, 11:45 AM",
    timestamp: "2025-07-07T11:45:00",
    school: "Sunrise Academy",
    reporter: "Mr. Ravi, Principal",
    category: "Safety",
    status: "Resolved",
    room: "Playground Area",
    description: "Broken fence posing risk to students",
    attachmentUrl: "/fence_issue.jpg",
  },
  {
    id: "JKL-320",
    date: "08 July 2025, 09:30 AM",
    timestamp: "2025-07-08T09:30:00",
    school: "Harmony Convent",
    reporter: "Ms. Latha, Teacher",
    category: "Electrical",
    status: "In Progress",
    room: "12th - Lab 2",
    description: "Power outage in computer lab",
    attachmentUrl: "/lab_issue.jpg",
  },
  {
    id: "MNO-118",
    date: "09 July 2025, 03:20 PM",
    timestamp: "2025-07-09T15:20:00",
    school: "Riverdale High",
    reporter: "John, Student",
    category: "Furniture",
    status: "Pending",
    room: "9th - Room 204",
    description: "Broken desk causing injury risk",
    attachmentUrl: "/desk_issue.jpg",
  },
  {
    id: "PQR-942",
    date: "10 July 2025, 10:10 AM",
    timestamp: "2025-07-10T10:10:00",
    school: "Lighthouse School",
    reporter: "Mrs. Fernandez, Teacher",
    category: "Water Supply",
    status: "Resolved",
    room: "Staff Room",
    description: "Drinking water tap leaking constantly",
    attachmentUrl: "/tap_issue.jpg",
  },
  {
    id: "STU-593",
    date: "11 July 2025, 01:00 PM",
    timestamp: "2025-07-11T13:00:00",
    school: "Evergreen International",
    reporter: "Principal Mehta",
    category: "Security",
    status: "In Progress",
    room: "Main Gate",
    description: "CCTV camera not working at main entrance",
    attachmentUrl: "/cctv_issue.jpg",
  },
  {
    id: "VWX-870",
    date: "12 July 2025, 04:40 PM",
    timestamp: "2025-07-12T16:40:00",
    school: "Oakridge School",
    reporter: "Ms. Radhika, Admin",
    category: "Cleanliness",
    status: "Pending",
    room: "Cafeteria",
    description: "Rodents spotted near food storage",
    attachmentUrl: "/rodent_issue.jpg",
  },
  {
    id: "YZA-003",
    date: "13 July 2025, 08:50 AM",
    timestamp: "2025-07-13T08:50:00",
    school: "Maple Leaf School",
    reporter: "Mr. Sohail, Sports Coach",
    category: "Sports Equipment",
    status: "Resolved",
    room: "Gym Room",
    description: "Damaged treadmill in the gym",
    attachmentUrl: "/treadmill_issue.jpg",
  }
];
