export const schools = [
  {
    id: "SCH-001",
    name: "GreenTown High School",
    district: "Eastwood",
    principal: "Mr. Danial",
    established: 1995,
    students: 850,
    staff: 65,
    address: "123 Green Road, Eastwood",
    contact: "greentown@example.com",
    phone: "9876543210",
    category: "Government",
    status: "Active",
    lastInspection: "2025-06-25T10:00:00",
    imageUrl: "/school_greentown.jpg",
  },
  {
    id: "SCH-002",
    name: "BlueBell Public School",
    district: "Riverside",
    principal: "Mrs. Anita",
    established: 2001,
    students: 740,
    staff: 58,
    address: "45 Blue Street, Riverside",
    contact: "bluebell@example.com",
    phone: "9876543211",
    category: "Private",
    status: "Active",
    lastInspection: "2025-07-10T14:00:00",
    imageUrl: "/school_bluebell.jpg",
  },
  {
    id: "SCH-003",
    name: "Sunrise Academy",
    district: "Northfield",
    principal: "Mr. Ravi",
    established: 1988,
    students: 920,
    staff: 72,
    address: "88 Sunrise Lane, Northfield",
    contact: "sunrise@example.com",
    phone: "9876543212",
    category: "Private",
    status: "Under Review",
    lastInspection: "2025-06-30T09:30:00",
    imageUrl: "/school_sunrise.jpg",
  },
  {
    id: "SCH-004",
    name: "Harmony Convent",
    district: "Westfield",
    principal: "Ms. Latha",
    established: 1990,
    students: 600,
    staff: 50,
    address: "234 Peace Ave, Westfield",
    contact: "harmony@example.com",
    phone: "9876543213",
    category: "Convent",
    status: "Active",
    lastInspection: "2025-07-05T12:00:00",
    imageUrl: "/school_harmony.jpg",
  },
  {
    id: "SCH-005",
    name: "Riverdale High",
    district: "Riverbank",
    principal: "Mr. John",
    established: 1975,
    students: 1100,
    staff: 85,
    address: "67 River Blvd, Riverbank",
    contact: "riverdale@example.com",
    phone: "9876543214",
    category: "Government",
    status: "Needs Attention",
    lastInspection: "2025-07-01T15:45:00",
    imageUrl: "/school_riverdale.jpg",
  },
  {
    id: "SCH-006",
    name: "Lighthouse School",
    district: "Beacon Town",
    principal: "Mrs. Fernandez",
    established: 2005,
    students: 510,
    staff: 42,
    address: "21 Beacon Road, Beacon Town",
    contact: "lighthouse@example.com",
    phone: "9876543215",
    category: "Private",
    status: "Active",
    lastInspection: "2025-07-09T10:15:00",
    imageUrl: "/school_lighthouse.jpg",
  },
  {
    id: "SCH-007",
    name: "Evergreen International",
    district: "Hillview",
    principal: "Principal Mehta",
    established: 2010,
    students: 650,
    staff: 60,
    address: "88 Hill Top Road, Hillview",
    contact: "evergreen@example.com",
    phone: "9876543216",
    category: "International",
    status: "Active",
    lastInspection: "2025-07-11T13:30:00",
    imageUrl: "/school_evergreen.jpg",
  },
  {
    id: "SCH-008",
    name: "Oakridge School",
    district: "Oak Valley",
    principal: "Ms. Radhika",
    established: 1999,
    students: 770,
    staff: 68,
    address: "56 Oak Circle, Oak Valley",
    contact: "oakridge@example.com",
    phone: "9876543217",
    category: "Private",
    status: "Active",
    lastInspection: "2025-07-12T16:00:00",
    imageUrl: "/school_oakridge.jpg",
  },
  {
    id: "SCH-009",
    name: "Maple Leaf School",
    district: "Maplewood",
    principal: "Mr. Sohail",
    established: 1992,
    students: 690,
    staff: 55,
    address: "99 Maple Ave, Maplewood",
    contact: "mapleleaf@example.com",
    phone: "9876543218",
    category: "Government Aided",
    status: "Active",
    lastInspection: "2025-07-13T08:30:00",
    imageUrl: "/school_mapleleaf.jpg",
  }
];
