export default () => ({
  KEYCLOAK_DOMAIN: process.env.KEYCLOAK_DOMAIN,
  KEYCLOAK_REALM: process.env.KEYCLOAK_REALM,
  KEYCLOAK_ADMIN_CLIENT_ID: process.env.KEYCLOAK_ADMIN_CLIENT_ID,
  KEYCLOAK_ADMIN_CLIENT_SECRET: process.env.KEYCLOAK_ADMIN_CLIENT_SECRET,
});
